# HLint configuration file
# https://github.com/ndmitchell/hlint

- ignore: {name: "Use String"}
- ignore: {name: "Redundant bracket", within: Test.Properties}
- ignore: {name: "Functor law"      , within: Test.Properties}
- ignore: {name: "Use <>"           , within: Main}

# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}
