# HLint configuration file
# https://github.com/ndmitchell/hlint

- arguments: [-XHaskell2010]

- ignore: {name: "Use String" , within: Test.Instances}

- group: {name: dollar     , enabled: true}
- group: {name: generalise , enabled: true}
