[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"
